/* Representatives City Search Data */

const westCities = [
  "Śrem",
  "Środa Wielkopolska",
  "Chodzież",
  "Czarnków-Trzcianka",
  "Gniezno",
  "Gostyń",
  "Grodzisk Wielkopolski",
  "Jarocin",
  "Kalisz",
  "Kępno",
  "Kościan",
  "Krotoszyn",
  "Leszno",
  "Międzychód",
  "Nowy Tomyśl",
  "Oborniki",
  "Ostrów Wielkopolski",
  "Ostrzeszów",
  "Piła",
  "Pleszew",
  "Poznań",
  "Rawicz",
  "Słupca",
  "Szamotuły",
  "Wągrowiec",
  "Wolsztyn",
  "Września",
  "Złotów",

  "Wrocław",
  "Środa Śląska",
  "Świdnica",
  "Bolesławiec",
  "Dzierżoniów",
  "Głogów",
  "Góra",
  "Jawor",
  "Jelenia Góra",
  "Karkonosze",
  "Kłodzko",
  "Kamienna",
  "Legnica",
  "Lubań",
  "Lubin",
  "Lwówek Śląski",
  "Milicz",
  "Oława",
  "Oleśnica",
  "Polkowice",
  "Strzelin",
  "Trzebnica",
  "Wałbrzych",
  "Wołów",
  "Złotoryja",
  "Ząbkowice",
  "Zgorzelec",

  "Żagań",
  "Żary",
  "Świebodzin",
  "Gorzów Wielkopolski",
  "Gorzów",
  "Krosno Odrzańskie",
  "Międzyrzecz",
  "Nowa Sól",
  "Słubice",
  "Strzelce-Drezdenko",
  "Sulęcin",
  "Wschowa",

  "Łobez",
  "Świdwin",
  "Świnoujście",
  "Białogard",
  "Choszczno",
  "Drawsko",
  "Goleniów",
  "Gryfice",
  "Gryfino",
  "Kamień",
  "Kołobrzeg",
  "Koszalin",
  "Myślibórz",
  "Police",
  "Pyrzyce",
  "Sławno",
  "Stargard",
  "Szczecinek",
  "Szczecin",
  "Wałcz",
];

const southCities = [
  "Busko",
  "Jędrzejów",
  "Kazimierza",
  "Kielce",
  "Końskie",
  "Opatów",
  "Ostrowiec",
  "Pińczów",
  "Sandomierz",
  "Skarżysko",
  "Starachowice",
  "Staszów",
  "Włoszczowa",

  "Bochnia",
  "Brzesko",
  "Chrzanów",
  "Dąbrowa",
  "Gorlice",
  "Kraków",
  "Limanowa",
  "Miechów",
  "Myślenice",
  "Nowy Sącz",
  "Nowy Targ",
  "Oświęcim",
  "Olkusz",
  "Proszowice",
  "Sucha",
  "Tarnów",
  "Tatra",
  "Wadowice",
  "Wieliczka",

  "Brzeg",
  "Głubczyce",
  "Kędzierzyn-Koźle",
  "Kluczbork",
  "Krapkowice",
  "Namysłów",
  "Nysa",
  "Olesno",
  "Opole",
  "Prudnik",
  "Strzelce",

  "Żory",
  "Żywiec",
  "Świętochłowice",
  "Będzin",
  "Bielsko-Biała",
  "Bielsko",
  "Bieruń-Lędziny",
  "Bytom",
  "Chorzów",
  "Cieszyn",
  "Częstochowa",
  "Dąbrowa Górnicza",
  "Gliwice",
  "Jastrzębie-Zdrój",
  "Jaworzno",
  "Kłobuck",
  "Katowice",
  "Lubliniec",
  "Mikołów",
  "Mysłowice",
  "Myszków",
  "Piekary Śląskie",
  "Pszczyna",
  "Racibórz",
  "Ruda Śląska",
  "Rybnik",
  "Siemianowice Śląskie",
  "Sosnowiec",
  "Tarnowskie Góry",
  "Tychy",
  "Wodzisław",
  "Zabrze",
  "Zawiercie",

  "Łańcut",
  "Bieszczady",
  "Brzozów",
  "Dębica",
  "Jarosław",
  "Jasło",
  "Kolbuszowa",
  "Krosno",
  "Leżajsk",
  "Lesko",
  "Lubaczów",
  "Mielec",
  "Nisko",
  "Przemyśl",
  "Przeworsk",
  "Ropczyce-Sędziszów",
  "Rzeszów",
  "Sanok",
  "Stalowa Wola",
  "Strzyżów",
  "Tarnobrzeg",
];

const centerCities = [
  "Łódź Wschód",
  "Łódź",
  "Łask",
  "Łęczyca",
  "Łowicz",
  "Bełchatów",
  "Brzeziny",
  "Kutno",
  "Opoczno",
  "Pabianice",
  "Pajęczno",
  "Piotrków Trybunalski",
  "Piotrków",
  "Poddębice",
  "Radomsko",
  "Rawa",
  "Sieradz",
  "Skierniewice",
  "Tomaszów Mazowiecki",
  "Wieluń",
  "Wieruszów",
  "Zduńska Wola",
  "Zgierz",

  "Koło",
  "Konin",
  "Turek",
  "Żnin",

  "Aleksandrów",
  "Świecie",
  "Brodnica",
  "Bydgoszcz",
  "Chełmno",
  "Golub-Dobrzyń",
  "Grudziądz",
  "Inowrocław",
  "Lipno",
  "Mogilno",
  "Nakło",
  "Radziejów",
  "Rypin",
  "Sępólno",
  "Toruń",
  "Tuchola",
  "Włocławek",
  "Wąbrzeźno",

  "Łęczna",
  "Łuków",
  "Świdnik",
  "Biłgoraj",
  "Biała Podlaska",
  "Chełm",
  "Hrubieszów",
  "Janów",
  "Kraśnik",
  "Krasnystaw",
  "Lubartów",
  "Lublin",
  "Opole Lubelskie",
  "Parczew",
  "Puławy",
  "Radzyń",
  "Ryki",
  "Tomaszów",
  "Włodawa",
  "Zamość",

  "Żuromin",
  "Żyrardów",
  "Łosice",
  "Białobrzegi",
  "Ciechanów",
  "Garwolin",
  "Gostynin",
  "Grójec",
  "Grodzisk Mazowiecki",
  "Kozienice",
  "Legionowo",
  "Lipsko",
  "Mława",
  "Maków",
  "Mińsk",
  "Nowy Dwór Mazowiecki",
  "Ostrów Mazowiecka",
  "Ostrołęka",
  "Otwock",
  "Płońsk",
  "Płock",
  "Piaseczno",
  "Pruszków",
  "Przasnysz",
  "Przysucha",
  "Pułtusk",
  "Radom",
  "Siedlce",
  "Sierpc",
  "Sochaczew",
  "Sokołów",
  "Szydłowiec",
  "Węgrów",
  "Wołomin",
  "Wyszków",
  "Zwoleń",

  "Łomża",
  "Augustów",
  "Białystok",
  "Bielsk",
  "Grajewo",
  "Hajnówka",
  "Kolno",
  "Mońki",
  "Sejny",
  "Siemiatycze",
  "Sokółka",
  "Suwałki",
  "Wysokie Mazowieckie",
  "Zambrów",

  "Bytów",
  "Chojnice",
  "Człuchów",
  "Gdańsk",
  "Gdynia",
  "Kartuzy",
  "Kościerzyna",
  "Kwidzyn",
  "Lębork",
  "Malbork",
  "Nowy Dwór Gdański",
  "Puck",
  "Słupsk",
  "Sopot",
  "Starogard",
  "Sztum",
  "Tczew",
  "Wejherowo",

  "Bartoszyce",
  "Braniewo",
  "Działdowo",
  "Ełk",
  "Elbląg",
  "Giżycko",
  "Gołdap",
  "Iława",
  "Kętrzyn",
  "Lidzbark",
  "Mrągowo",
  "Nidzica",
  "Nowe Miasto Lubawskie",
  "Olecko",
  "Olsztyn",
  "Ostróda",
  "Pisz",
  "Szczytno",
  "Węgorzewo",
];

const cityRegionData = [
  ...westCities.map(function (city) {
    return {
      city: city,
      region: "west",
      representative: "Tomasz Krupianik",
    };
  }),

  ...southCities.map(function (city) {
    return {
      city: city,
      region: "south",
      representative: "Mirosław Łaszczyca",
    };
  }),

  ...centerCities.map(function (city) {
    return {
      city: city,
      region: "center",
      representative: "Jarosław Manowiecki",
    };
  }),

  {
    city: "Warszawa",
    mapName: "Warszawa",
    region: "center",
    representative: "Jarosław Manowiecki",
  },
  {
    city: "Warszawa Zachodnia",
    mapName: "Warszawa Zachodnia",
    region: "center",
    representative: "Jarosław Manowiecki",
  },
  {
    city: "Zielona Góra",
    mapName: "Zielona Góra",
    region: "west",
    representative: "Tomasz Krupianik",
  },
];
